# Generated by Django 6.0.2 on 2026-03-01 19:05

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("education", models.JSONField(default=list)),
                ("skills", models.JSONField(default=list)),
                ("interests", models.JSONField(default=list)),
                ("career_goal", models.CharField(blank=True, max_length=255)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("clear", "I know what I want"),
                            ("confused", "I need guidance"),
                        ],
                        default="confused",
                        max_length=20,
                    ),
                ),
                ("target_role", models.CharField(blank=True, max_length=255)),
                ("target_timeline", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "preferred_work_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("remote", "Remote"),
                            ("onsite", "On-site"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "Free only"),
                            ("low", "Under $100"),
                            ("medium", "Under $500"),
                            ("high", "No limit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("onboarding_step", models.IntegerField(default=0)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
